config/routes.rb
Devise::Application.routes.draw do
  resources :subcategories do
    get   "load_subcategories",     :on=> :collection
 end

  resources :categories do 
    
  end

  resources :products 

  devise_for :users

  get "homes/index"

   root :to => "products#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
has_many :subcategories



end

app/models/product.rb
class Product < ActiveRecord::Base
belongs_to :subcategory
has_attached_file :file
has_attached_file :avatar
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
  belongs_to :categorie
  has_many :products
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation,:role, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.xml
  def index
    @categories = Category.all
@categories = Category.paginate(:page => params[:page],:per_page => 2)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.xml
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.xml
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.xml
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to(@category, :notice => 'Category was successfully created.') }
        format.xml  { render :xml => @category, :status => :created, :location => @category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.xml
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to(@category, :notice => 'Category was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.xml
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to(categories_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.xml
before_filter :authenticate_user!
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @products }
    end
  end

  # GET /products/1
  # GET /products/1.xml
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/new
  # GET /products/new.xml
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.xml
  def create
    @product = Product.new(params[:product])
   puts "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$",params    
    respond_to do |format|
      if @product.save
        format.html { redirect_to(@product, :notice => 'Product was successfully created.') }
        format.xml  { render :xml => @product, :status => :created, :location => @product }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.xml
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to(@product, :notice => 'Product was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.xml
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to(products_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  # GET /subcategories
  # GET /subcategories.xml
  def index
    @subcategories = Subcategory.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @subcategories }
    end
  end

 def load_subcategories
   if request.xhr?
    @subcategories = Subcategory.select('id,name').where(:category_id =>params[:id].to_i) 
    respond_to do |format|
      format.js
    end
   end
  end
  # GET /subcategories/1
  # GET /subcategories/1.xml
  def show
    @subcategory = Subcategory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @subcategory }
    end
  end

  # GET /subcategories/new
  # GET /subcategories/new.xml
  def new
    @subcategory = Subcategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @subcategory }
    end
  end

  # GET /subcategories/1/edit
  def edit
    @subcategory = Subcategory.find(params[:id])
  end

  # POST /subcategories
  # POST /subcategories.xml
  def create
    @subcategory = Subcategory.new(params[:subcategory])

    respond_to do |format|
      if @subcategory.save
        format.html { redirect_to(@subcategory, :notice => 'Subcategory was successfully created.') }
        format.xml  { render :xml => @subcategory, :status => :created, :location => @subcategory }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @subcategory.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /subcategories/1
  # PUT /subcategories/1.xml
  def update
    @subcategory = Subcategory.find(params[:id])

    respond_to do |format|
      if @subcategory.update_attributes(params[:subcategory])
        format.html { redirect_to(@subcategory, :notice => 'Subcategory was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @subcategory.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /subcategories/1
  # DELETE /subcategories/1.xml
  def destroy
    @subcategory = Subcategory.find(params[:id])
    @subcategory.destroy

    respond_to do |format|
      format.html { redirect_to(subcategories_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= category.description %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />
<%= will_paginate @categories %>
<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>

<p>
  <b>Description:</b>
  <%= @category.description %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/homes/index.html.erb
<h1>Homes#index</h1>
<p>Find me in app/views/homes/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Devise</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<% flash.each do |key, msg| %>
     <%=content_tag :div, msg, :class =>"flash_#{key}", :id => "app_flash"%>
<% end %>


<%if user_signed_in? %>
  Welcome to <%= current_user%>|<%= link_to "Sign Out",destroy_user_session_path %>
  <% else %> 
    <div align="right">    <%= link_to "Login", new_user_session_path %>&nbsp;&nbsp;
        &nbsp;|&nbsp;
        <%= link_to "Register", new_user_registration_path %>
  <% end %>
  </div>
<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<% if current_user.role == "admin" %>
<%= form_for(@product,:html => { :multipart => true } ) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= f.collection_select(:category_id, Category.find(:all), :id, :name ,{:prompt=> 'Select Category'}, :class => 'droplist') %>
<br>
<div id="subcategories">
<%= f.collection_select( :subcategory_id, [], :id, :name ,{:prompt=> 'Select Subcategory'}, :class => 'droplist') %><br>
</div>  
<div class="field">
    <%= f.label :productname %><br />
    <%= f.text_field :productname %>
  </div>
  <div class="field">


    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.text_field :weight %>
  </div>

<div class="field">
	<%= f.label :Image %>
	<%= f.file_field :avatar %>
	</div><br />

<div class="field">
	<%= f.label :File %>
	<%= f.file_field :file %>
	</div><br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<% else%> You are not authorize to use this page.
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Productname</th>
    <th>Price</th>
    <th>Weight</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.productname %></td>
    <td><%= product.price %></td>
    <td><%= product.weight %></td>
  <% if current_user.role == "co-admin" %>  <td><%= link_to 'Show', product %></td>
  <% elsif current_user.role == "admin"%>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, :confirm => 'Are you sure?', :method => :delete %></td>
 <td><%= link_to image_tag("/images/show.jpg"), employee %></td>
  <% end%>
  </tr>
<% end %>
</table>

<br />

<% if current_user.role == "admin" %><%= link_to 'New Product', new_product_path %><%end%>

app/views/products/load_subcategories.js.erb
 $("#subcategories").html("<%= escape_javascript(collection_select :product,:subcategory_id,@subcategories,:id,:name,:prompt=>"Select a Subcategory", :class => 'droplist')%>");

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Productname:</b>
  <%= @product.productname %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>

<p>
  <b>Weight:</b>
  <%= @product.weight %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/subcategories/_form.html.erb
<%= form_for(@subcategory) do |f| %>
  <% if @subcategory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subcategory.errors.count, "error") %> prohibited this subcategory from being saved:</h2>

      <ul>
      <% @subcategory.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= f.collection_select :categorie_id, Category.all, :id, :name ,{:prompt=> 'Select Category'} %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subcategories/edit.html.erb
<h1>Editing subcategory</h1>

<%= render 'form' %>

<%= link_to 'Show', @subcategory %> |
<%= link_to 'Back', subcategories_path %>

app/views/subcategories/index.html.erb
<h1>Listing subcategories</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Categorie</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subcategories.each do |subcategory| %>
  <tr>
    <td><%= subcategory.name %></td>
    <td><%= subcategory.description %></td>
    <td><%= link_to 'Show', subcategory %></td>
    <td><%= link_to 'Edit', edit_subcategory_path(subcategory) %></td>
    <td><%= link_to 'Destroy', subcategory, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Subcategory', new_subcategory_path %>

app/views/subcategories/load_subcategories.js.erb
 $("#subcategories").html("<%= escape_javascript(collection_select :product,:subcategory_id,@subcategories,:id,:name,:prompt=>"Select a Subcategory", :class => 'droplist')%>");

app/views/subcategories/new.html.erb
<h1>New subcategory</h1>

<%= render 'form' %>

<%= link_to 'Back', subcategories_path %>

app/views/subcategories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @subcategory.name %>
</p>

<p>
  <b>Description:</b>
  <%= @subcategory.description %>
</p>



<%= link_to 'Edit', edit_subcategory_path(@subcategory) %> |
<%= link_to 'Back', subcategories_path %>